fullnameOverride: fdm-monster

podSecurityContext:
  fsGroup: 1000

deployment:
  image:
    repository: fdmmonster/fdm-monster
    tag: "2.1.1"
  ports:
    http: 4000

config:
  TZ: Europe/Brussels
  SERVER_PORT: "4000"
  NODE_ENV: production
  MEDIA_PATH: /app/data/media
  DATABASE_PATH: /app/data/database
  OVERRIDE_JWT_SECRET: <secret:kv/data/apps/fdm-monster~jwt-secret>

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi

ingress_internal_secure:
  host: fdm-monster.<secret:kv/data/domains~domain>
  port: http

storage:
  - mountPath: /app/data
    size: 5Gi
    type: longhorn
    volumeName: fdm-monster-data
    nameSuffix: data
