apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: kube-system
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        checksum/config: {{ include "cloudflared.config" . | sha256sum }}
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.2.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: cert
              mountPath: /etc/cloudflared
              readOnly: true
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 25Mi
          #   limits:
          #     cpu: 120m
          #     memory: 30Mi
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Prefer to run on same nodes as external Traefik for performance
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: traefik-external
                topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Prefer Cloudflare tunnel replicas on different nodes for HA
            - weight: 90
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: cloudflared
                topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Prefer non-Pi nodes for better performance
            - weight: 80
              preference:
                matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - rpi
      volumes:
        - name: creds
          secret:
            secretName: tunnel-credentials
        - name: cert
          secret:
            secretName: tunnel-pem
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: kube-system
data:
  config.yaml: |
{{ include "cloudflared.config" . | indent 4 }}
