apiVersion: v1
kind: Service
metadata:
  name: traefik-external-prometheus
  namespace: kube-system
  labels:
    app: traefik-external
spec:
  type: ClusterIP
  selector:
    app: traefik-external
  ports:
  - port: 9100
    name: metrics
    targetPort: metrics
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: traefik-external
  name: traefik-external
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: metrics
    path: /metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: traefik-exporter
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: traefik-external