apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - image: prom/snmp-exporter:v0.26.0
        name: snmp-exporter
        args:
          - '--config.file=/etc/snmp_exporter/snmp.yml'
        ports:
        - containerPort: 9116
          name: metrics
        volumeMounts:
        - name: snmp-exporter-dir
          mountPath: /etc/snmp_exporter/
        resources: {}
      volumes:
        - name: snmp-exporter-dir
          configMap:
            name: snmp-volume-synology-homenas
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmp-exporter
  name: snmp-exporter
  namespace: monitoring
spec:
  ports:
  - name: snmp-exporter-metrics
    port: 9116
    protocol: TCP
    targetPort: metrics
  selector:
    app: snmp-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: snmp-exporter
    monitoring: yess
  name: snmp-exporter-gobelijn
  namespace: monitoring
spec:
  jobLabel: snmp-exporter
  selector:
    matchLabels:
      app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 5s
    port: snmp-exporter-metrics
    path: "/snmp"
    targetPort: 9116
    params:
      module:
      - synology
      target:
      - <secret:kv/data/external-ips~gobelijn>
    relabelings:
      - action: replace
        regex: (.*)
        replacement: Gobelijn
        sourceLabels:
        - instance
        targetLabel: instance
