fullnameOverride: cloudbeaver
deployment:
  image:
    repository: dbeaver/cloudbeaver
    tag: 26.0.2
  ports:
    ingress: 8978
config:
  CLOUDBEAVER_SERVICE_PORT_8978_TCP: 8978
  CLOUDBEAVER_SERVICE_PORT: 8978
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
ingress_internal:
  host: cloudbeaver.<secret:kv/data/domains~local>
  port: ingress
ingress_internal_secure:
  host: cloudbeaver.<secret:kv/data/domains~domain>
  port: ingress
storage:
  - mountPath: /opt/cloudbeaver/workspace
    size: 512Mi
    type: longhorn
    namesuffix: workspace
    volumeName: cloudbeaver-workspace
    protect: true
