fullnameOverride: cloudbeaver
deployment:
  image:
    repository: dbeaver/cloudbeaver
    tag: 24.3.4
  ports:
    ingress: 8978
config:
  CLOUDBEAVER_SERVICE_PORT_8978_TCP: 8978
  CLOUDBEAVER_SERVICE_PORT: 8978
ingress_internal:
  host: cloudbeaver.<secret:kv/data/domains~local>
  port: ingress
storage:
  - mountPath: /opt/cloudbeaver/workspace
    size: 5Gi
    type: nfs-client

