fullnameOverride: flaresolverr
deployment:
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: v3.4.6
  ports:
    web: 8191
config:
  TZ: Europe/Brussels
  PUID: 1000
  PGID: 1000

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 768Mi

podSecurityContext:
  fsGroup: 1000
probes:
  liveness:
    tcpSocket:
      port: web
    initialDelaySeconds: 30
    periodSeconds: 10
