repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
        exclude: ^workload/.*\/.*\.yaml$
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace
