apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwakeword-data
  namespace: smarthome
  annotations:
    nfs.io/storage-path: "openwakeword/data"
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi