apiVersion: v1
kind: Service
metadata:
  labels:
    app: openwakeword
  name: openwakeword
  namespace: smarthome
spec:
  ports:
  - name: openwakeword
    port: 10400
    targetPort: openwakeword
  selector:
    app: openwakeword
  type: ClusterIP
