apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openwakeword
  namespace: smarthome
spec:
  serviceName: openwakeword
  selector:
    matchLabels:
      app: openwakeword
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
        - name: openwakeword
          image: rhasspy/wyoming-openwakeword:1.10.0@sha256:3165a5cd8aef84beb882e640aa1f5c01c97f8c0b1f50016164ecdf2ab65d033a
          args:
            - --preload-model
            - hey_jarvis
          env:
          - name: TZ
            value: Europe/Brussels
          resources: {}
          ports:
            - containerPort: 10400
              name: openwakeword
              protocol: TCP
          volumeMounts:
            - name: openwakeword-data
              mountPath: /data
      volumes:
          - name: openwakeword-data
            persistentVolumeClaim:
              claimName: openwakeword-data