apiVersion: v1
kind: Secret
metadata:
  name: keel-pull-secrets
  namespace: kube-system      
type: Opaque
data:
  .dockerconfigjson: <secret:kv/data/system/kube-system/keel~docker-registry | base64>
