apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage

resources:
  - smb-operator-config.yaml
  - smb-operator-migration.yaml
  - smb-operator-deploy.yaml
  - smb-credentials-secret.yaml

configMapGenerator:
  - name: smb-operator-python
    namespace: storage
    files:
      - smb_operator_v2.py
    options:
      disableNameSuffixHash: false

labels:
  - pairs:
      app.kubernetes.io/part-of: longhorn-smb-operator
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
