---
apiVersion: v1
kind: Secret
metadata:
  name: smb-credentials
  namespace: storage
type: Opaque
stringData:
  password: <secret:kv/data/system/storage/longhorn-smb-operator~password>
  username: <secret:kv/data/system/storage/longhorn-smb-operator~user>
  ip: <secret:kv/data/system/storage/longhorn-smb-operator~ip>
