---
apiVersion: v1
kind: Secret
metadata:
  name: smb-credentials
  namespace: storage
type: Opaque
stringData:
  password: <secret:kv/data/storage/longhorn-nfs~password>
  username: <secret:kv/data/storage/longhorn-nfs~user>
  ip: <secret:kv/data/storage/longhorn-nfs~ip>
