fullnameOverride: mqtt-playground
statefullset:
  image:
    repository: ghcr.io/coollision/mqtt-go-playground
    tag: latest
    imagePullPolicy: Always
config:
  LOGLEVEL: INFO
  MQTT_BROKERADDRESS: <secret:kv/data/smarthome/mqtt-go-playground~BrokerAddress>
  MQTT_BROKERID: <secret:kv/data/smarthome/mqtt-go-playground~BrokerId>
  MQTT_BROKERUSER: <secret:kv/data/smarthome/mqtt-go-playground~BrokerUser>
  MQTT_BROKERPASSWORD: <secret:kv/data/smarthome/mqtt-go-playground~BrokerPassword>

keel:
  policy: force
  pollSchedule: "@every 1m"

disableService: true