apiVersion: v2
name: keel
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
maintainers:
  - name: coollision
    email: Coollision@users.noreply.github.com
dependencies:
  - name: keel
    version: 1.0.3
    repository: https://charts.keel.sh

