keel:
  image:
    repository: fardjad/keel
    tag: latest
  basicauth:
    enabled: true
    user: <secret:kv/data/kube-system/keel~user>
    password: <secret:kv/data/kube-system/keel~password>

  service:
    enabled: true
    type: ClusterIP