keel:
  image:
    repository: fardjad/keel
    tag: latest
  basicauth:
    enabled: true
    user: <secret:kv/data/kube-system/keel~user>
    password: <secret:kv/data/kube-system/keel~password>

  dockerRegistry:
    enabled: true
    name: "keel-pull-secrets"
    key: ".dockerconfigjson"

  service:
    enabled: true
    type: ClusterIP

  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu: 25m
      memory: 45Mi