apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-app-config
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://github.com/Coollision/homelab-config.git"
    path: system
    targetRevision: master
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      # selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
