{{define "argocd-vault-replacer-credentials" -}}
apiVersion: v1
data:
  ARGOCD_ENV_VAULT_ADDR: {{ .Values.vault.addr | b64enc | quote }}
  ARGOCD_ENV_VAULT_ROLE: {{ .Values.vault.role | b64enc | quote }}
kind: Secret
metadata:
  name: argocd-vault-replacer-credentials
  namespace: argocd
type: Opaque
{{- end}}
{{include "argocd-vault-replacer-credentials" . }}