fullnameOverride: prefetcharr
deployment:
  image:
    repository: phueber/prefetcharr
    tag: sha256:4688f067f63f15720309ec8584136d421e370e046d19693a4b6b880d4be3e68f

config:
  TZ: Europe/Brussels
  MEDIA_SERVER_TYPE: plex
  # Jellyfin/Emby/Plex baseurl
  MEDIA_SERVER_URL: https://plex.declerck.dev
  # Jellyfin/Emby API key or plex server token
  MEDIA_SERVER_API_KEY: <secret:kv/data/services~plex_token>
  # Sonarr baseurl
  SONARR_URL: http://sonarr.<secret:kv/data/domains~local>
  # Sonarr API key
  SONARR_API_KEY: <secret:kv/data/services~sonarr_api_key>
  # Logging directory
  # LOG_DIR: /log
  # Log level
  RUST_LOG: prefetcharr=debug
  # Polling interval in seconds
  INTERVAL: 900
  # The last <NUM> episodes trigger a search
  REMAINING_EPISODES: 4
  # Optional: Only monitor sessions for specific user IDs or names
  # USERS: john,12345,Axel F
  # Optional: Only monitor sessions for specific libraries
  # LIBRARIES: TV Shows,Anime