{
 "title": "k3s Monitoring Overvieuw",
 "description": "Monitor a K3s cluster using Prometheus TSDB.  Shows overall cluster CPU / Memory / Disk usage as well as individual pod statistics. ",
 "tags": [
  "additional",
  "overview"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) - sum(node_memory_MemFree_bytes{job=\"node-exporter\"}+node_memory_Buffers_bytes{job=\"node-exporter\"}+node_memory_Cached_bytes{job=\"node-exporter\"})) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) * 100"
    }
   ]
  },
  {
   "title": "Up Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"kubelet\",metrics_path=\"/metrics\"}) BY (job)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[90s])) * 100))"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{instance!~\".*node-exporter.monitoring.svc:9100\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Core Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg by (job) (up{job=~\"kube-dns|kubelet|traefik.*|apiserver|kube-controller-manager|kube-scheduler|kube-proxy\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(pod)(node_memory_MemTotal_bytes{instance!~\".*node-exporter.*\"} - (node_memory_MemFree_bytes{instance!~\".*node-exporter.*\"}+node_memory_Buffers_bytes{instance!~\".*node-exporter.*\"}+node_memory_Cached_bytes{instance!~\".*node-exporter.*\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname!=\"Watchdog\",severity!=\"none\"}"
    }
   ]
  },
  { "title": "Alarms", "type": "alertlist", "gridPos": { "h": 9, "w": 5, "x": 12, "y": 19 } },
  {
   "title": "Cluster Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{device=~\"/dev/.*\"}) ) / sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Up Nodes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(up{job=\"kubelet\",metrics_path=\"/metrics\"}) BY (job, node)",
     "legendFormat": " {{node}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum without(pod) (rpi_cpu_temperature_celsius)",
     "legendFormat": "cpu: {{instance}}"
    },
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", service=\"monitoring-node-exporter\"})",
     "legendFormat": "cpu: {{instance}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10,sum by (pod)(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_rss{name=~\".+\"}) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_network_transmit_bytes_total{pod=~\".+\"}[5m])) by (pod))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_network_receive_bytes_total{pod=~\".+\"}[5m])) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network i/o",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (kubernetes_pod_name) (rate (container_network_receive_bytes_total{name!=\"\", kubernetes_pod_name=~\".*\"}[1m]) ))",
     "legendFormat": "Receive Traffic"
    },
    {
     "expr": "sort_desc(sum by (kubernetes_pod_name) (rate (container_network_transmit_bytes_total{name!=\"\", kubernetes_pod_name=~\".*\"}[1m]) ))",
     "legendFormat": "Transmit Traffic"
    }
   ]
  }
 ]
}