{
 "title": "Synology SNMP DashBoard Copy",
 "description": "A Dashboard for Synology NAS based on SNMP and Prometheus",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "query_result(up{job=\"snmp-exporter\"})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sum by (ifName)(synology_ifInOctets{job=\"snmp-exporter\",  instance=\"$Device\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "system info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synology_modelName{instance=\"$Device\"}"
    },
    {
     "expr": "synology_version{instance=\"$Device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "synology_serialNumber{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "synology_systemStatus{instance=\"$Device\"}",
     "legendFormat": "system status"
    },
    {
     "expr": "synology_powerStatus{instance=\"$Device\"}",
     "legendFormat": "power"
    },
    {
     "expr": "synology_systemFanStatus{instance=\"$Device\"}",
     "legendFormat": "fan status"
    },
    {
     "expr": "synology_cpuFanStatus{instance=\"$Device\"}",
     "legendFormat": "cpu fan status"
    },
    {
     "expr": "synology_upgradeAvailable{instance=\"$Device\"}",
     "legendFormat": "are there updates?"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "synology_diskStatus{instance=\"$Device\"}",
     "legendFormat": "{{diskID}}:"
    }
   ]
  },
  {
   "title": "used disk space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((synology_raidTotalSize{instance=\"$Device\", raidName=~\"Volume.*\"} - synology_raidFreeSize{instance=\"$Device\", raidName=~\"Volume.*\"} )  / synology_raidTotalSize{instance=\"$Device\", raidName=~\"Volume.*\"} ) * 100",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "raidStatus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "synology_raidStatus{instance=\"$Device\"}",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  { "title": "base info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum without(pod)(synology_diskTemperature{instance=\"$Device\"})",
     "legendFormat": "{{diskID}}"
    },
    {
     "expr": "sum without(pod)(synology_temperature{instance=\"$Device\"})",
     "legendFormat": "enclosureTemp"
    }
   ]
  },
  {
   "title": "Trafick of $Interface Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without(pod) (irate(synology_ifHCInOctets{job='snmp-exporter',instance='$Device', ifName=~'$Interface'}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum without(pod)(irate(synology_ifHCOutOctets{job='snmp-exporter',instance='$Device', ifName=~'$Interface'}[5m]) )",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(pod) (synology_laLoadInt{instance=\"$Device\"})\n",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  { "title": "from Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Login Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(hostname) (count_over_time({job=\"syslog\", service_name=\"Connection\"} |= `failed to sign in` [5m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}