apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: homeassistant
    path: add-bmw-api-config.yaml