homeassistantdb:
  syncWave: -10
  fullnameOverride: homeassistant-db
  statefullset:
    image:
      repository: mariadb
      tag: 12.0.2
    ports:
      mysql: 3306
  config:
    ServerName: mariadb
    MYSQL_ROOT_PASSWORD: <secret:kv/data/smarthome/homeassistant-db~root-password>
    MYSQL_AUTO_UPGRADE: Enabled
    MYSQL_DATABASE: <secret:kv/data/smarthome/homeassistant-db~name>
    MYSQL_USER: <secret:kv/data/smarthome/homeassistant-db~user>
    MYSQL_PASSWORD: <secret:kv/data/smarthome/homeassistant-db~password>
  storage:
    - mountPath: /var/lib/mysql
      storagePath: homeassistant-db/data
      size: 30Gi
      type: nfs-client
  probes:
    livenessProbe:
      exec:
        command:
        - mysqladmin
        - ping
      initialDelaySeconds: 40
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 4
    readinessProbe:
      exec:
        command:
        - mysqladmin
        - ping
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 4
  resources: 
    requests:
      memory: "600Mi"
      cpu: "500m"
    limits:
      memory: "800Mi"
      cpu: "1200m"
  labels:
    app.kubernetes.io/component: homeassistant-db
  affinity:
    node:
      preferred:
        - weight: 50
          matchExpressions:
            - key: type
              operator: In
              values:
                - mini

homeassistant:
  fullnameOverride: homeassistant
  statefullset:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2025.10.4
    ports:
      web: 8123
  config:
    TZ: Europe/Brussels
  ingress_internal:
    host: homeassistant.<secret:kv/data/domains~local>
    port: web
  ingress_internal_secure:
    host: homeassistant.<secret:kv/data/domains~domain>
    port: web
  ingress_external_secure:
    host: homeassistant.<secret:kv/data/domains~domain>
    port: web
  storage:
    - mountPath: /config
      storagePath: homeassistant/config
      size: 30Gi
      type: nfs-client
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  imagePreSync: true
  serviceIp: <secret:kv/data/smarthome/homeassistant~ip>
  probes:
    liveness:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 60
      periodSeconds: 10 
      timeoutSeconds: 5
      failureThreshold: 5
    readiness:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 5

  # resources: 
  #   requests:
  #     memory: "600Mi"
  #     cpu: "500m"
  #   limits:
  #     memory: "800Mi"
  #     cpu: "1200m"
  labels:
    app.kubernetes.io/component: homeassistant
  
  affinity:
    pod:
      preferred:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - homeassistant-db
            topologyKey: kubernetes.io/hostname