homeassistantdb:
  syncWave: -10
  fullnameOverride: homeassistant-db
  statefullset:
    image:
      repository: mariadb
      tag: 11.5.2@sha256:4a1de8fa2a929944373d7421105500ff6f889ce90dcb883fbb2fdb070e4d427e
    ports:
      mysql: 3306
  config:
    ServerName: mariadb
    MYSQL_ROOT_PASSWORD: <secret:kv/data/smarthome/homeassistant-db~root-password>
    MYSQL_AUTO_UPGRADE: Enabled
    MYSQL_DATABASE: <secret:kv/data/smarthome/homeassistant-db~name>
    MYSQL_USER: <secret:kv/data/smarthome/homeassistant-db~user>
    MYSQL_PASSWORD: <secret:kv/data/smarthome/homeassistant-db~password>
  storage:
    - mountPath: /var/lib/mysql
      storagePath: homeassistant-db/data
      size: 30Gi
      type: nfs-client
  probes:
    livenessProbe:
      exec:
        command:
        - mysqladmin
        - ping
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
        - mysqladmin
        - ping
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  resources: 
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "700Mi"
      cpu: "1000m"
  labels:
    app.kubernetes.io/component: homeassistant-db

homeassistant:
  fullnameOverride: homeassistant
  statefullset:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.10.3@sha256:a880ef8e77f34b694668e508ecb109b260948025c9ef71073ece9bc809155347
    ports:
      web: 8123
  config:
    TZ: Europe/Brussels
  ingress_internal:
    host: homeassistant.<secret:kv/data/domains~local>
    port: web
  ingress_internal_secure:
    host: homeassistant.<secret:kv/data/domains~domain>
    port: web
  ingress_external_secure:
    host: homeassistant.<secret:kv/data/domains~domain>
    port: web
  storage:
    - mountPath: /config
      storagePath: homeassistant/config
      size: 30Gi
      type: nfs-client
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  imagePreSync: true
  serviceIp: <secret:kv/data/smarthome/homeassistant~ip>
  probes:
    liveness:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 30
      periodSeconds: 10 
  labels:
    app.kubernetes.io/component: homeassistant