promtail:
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://logging-loki:3100/loki/api/v1/push
        tenant_id: 1

loki:
  deploymentMode: SingleBinary
  loki:
    storage:
      type: filesystem
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem # we're storing on filesystem so there's no real persistence here.
        schema: v13
  singleBinary:
    replicas: 1
    persistence:
      storageClass: nfs-client-name-path
  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0
  
  chunksCache:
    resources:
      requests:
        memory: 1Gi
    limits:
      memory: 1Gi