 nfs-subdir-external-provisioner:
  replicaCount: 2
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: <secret:kv/data/storage/nfs~server-path>
    mountOptions: 
      - hard
      - nfsvers=4.1
      
  storageClass:
    pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
    archiveOnDelete: false
    onDelete: retain
    name: nfs-client

  resources:
    requests:
      cpu: 10m
      memory: 30Mi
    limits:
      cpu: 25m
      memory: 45Mi