apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: smarthome
  annotations:
    nfs.io/storage-path: "whisper/data"
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-download
  namespace: smarthome
  annotations:
    nfs.io/storage-path: "whisper/download"
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi