fullnameOverride: "vault"
vault:
  server:
    extraLabels:
      preventDeschedule: "true"
    dataStorage:
      enabled: true
      storageClass: "nfs-client-name-path"
      size: "10Gi"
      mountPath: "/vault/data"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: NotIn
              values:
              - rpi
    # serviceAccount:
    #   createSecret: true
  ui:
    enabled: true

ingress_internal:
  host: vault.<secret:kv/data/domains~local>
