fullnameOverride: "vault"
vault:
  server:
    dataStorage:
      enabled: true
      storageClass: "nfs-client-name-path"
      size: "10Gi"
      mountPath: "/vault/data"

    # serviceAccount:
    #   createSecret: true
    labels:
      critical-service: "true"
  ui:
    enabled: true

ingress_internal:
  host: vault.<secret:kv/data/domains~local>
