fullnameOverride: "vault"

storage:
  - nameSuffix: data
    size: 128Mi
    type: longhorn
    volumeName: vault-data
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    protect: true

vault:
  server:
    extraLabels:
      preventDeschedule: "true"
    dataStorage:
      enabled: false
      mountPath: "/vault/data"
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vault-data
    volumeMounts:
      - name: data
        mountPath: "/vault/data"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: NotIn
              values:
              - rpi
  # serviceAccount:
  #   createSecret: true
  ui:
    enabled: true

ingress_internal:
  host: vault.<secret:kv/data/domains~local>
