apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto-mqtt
  namespace: smarthome
spec:
  ports:
  - name: mqtt
    port: 1880
    targetPort: mqtt
    protocol: TCP
  selector:
    app: mosquitto
  type: LoadBalancer
  # enable loadBalancer ip and set fixed dns to run multiple incstances
  loadBalancerIP: <secret:kv/data/smarthome/mosquito~ip>