apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-manyfold
  namespace: apps
spec:
  name: manyfold
  owner: manyfold_user
  cluster:
    name: apps-db-pg
  databaseReclaimPolicy: retain
