# CNPG role credentials for apps-db-pg
apiVersion: v1
kind: Secret
metadata:
  name: pgrole-manyfold
  namespace: apps
type: kubernetes.io/basic-auth
stringData:
  username: manyfold_user
  password: <secret:kv/data/apps/manyfold~db_password>
