wordpress:
  fullnameOverride: cv-frank-wp
  deployment:
    image:
      repository: wordpress
      tag: 6.6.1
    ports:
      wordpress: 80
  config:
    WORDPRESS_DB_HOST: cv-frank-mysql-service
    WORDPRESS_DB_NAME:
      secretKeyRef:
        name: cv-frank-mysql-wp
        key: db_name
    WORDPRESS_DB_USER: 
      secretKeyRef:
        name: cv-frank-mysql-wp
        key: db_user
    WORDPRESS_DB_PASSWORD: 
      secretKeyRef:
        name: cv-frank-mysql-wp
        key: db_user_pass
  ingress_internal:
    host: cv-frank.<secret:kv/data/domains~local>
    port: wordpress
  storage:
    - mountPath: /var/www/html
      storagePath: cv-frank/data
      size: 5Gi
      type: nfs-client
  secrets:
    - name: cv-frank-mysql-wp
      secret_kv:
        db_name: <secret:kv/data/wordpress/vloerwerken-schollaert~db_name>
        db_user: <secret:kv/data/wordpress/vloerwerken-schollaert~db_user>
        db_user_pass: <secret:kv/data/wordpress/vloerwerken-schollaert~db_user_pass>

mysql:
  fullnameOverride: cv-frank-mysql
  deployment:
    image:
      repository: yobasystems/alpine-mariadb
      tag: 10.11.8
    ports:
      mysql: 3306
  config:
    MYSQL_ROOT_PASSWORD:
      secretKeyRef:
        name: cv-frank-mysql
        key: db_root_pass
    MYSQL_DATABASE:
      secretKeyRef:
        name: cv-frank-mysql-wp
        key: db_name
    MYSQL_USER: 
      secretKeyRef:
        name: cv-frank-mysql-wp
        key: db_user
    MYSQL_PASSWORD: 
      secretKeyRef:
        name: cv-frank-mysql-wp
        key: db_user_pass
  storage:
    - mountPath: /var/lib/mysql
      storagePath: cv-frank/sql
      size: 2Gi
      type: nfs-client
  secrets:
    - name: cv-frank-mysql
      secret_kv:
        db_root_pass: <secret:kv/data/wordpress/vloerwerken-schollaert~db_root_pass>