vaultwardendb:
  syncWave: -10
  fullnameOverride: vaultwarden-db
  statefullset:
    image:
      repository: mariadb
      tag: 11.6.2
    ports:
      mysql: 3306
  config:
    ServerName: mariadb
    MYSQL_ROOT_PASSWORD: <secret:kv/data/secrets/vaultwarden-db~root-password>
    MYSQL_AUTO_UPGRADE: Enabled
    MYSQL_DATABASE: <secret:kv/data/secrets/vaultwarden-db~name>
    MYSQL_USER: <secret:kv/data/secrets/vaultwarden-db~user>
    MYSQL_PASSWORD: <secret:kv/data/secrets/vaultwarden-db~password>
  storage:
    - mountPath: /var/lib/mysql
      storagePath: vaultwarden/db
      size: 10Gi
      type: nfs-client
  probes:
    livenessProbe:
      exec:
        command:
        - mysqladmin
        - ping
      initialDelaySeconds: 40
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 4
    readinessProbe:
      exec:
        command:
        - mysqladmin
        - ping
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 4
  resources:
    requests:
      memory: "600Mi"
      cpu: "500m"
    limits:
      memory: "800Mi"
      cpu: "1200m"
  labels:
    app.kubernetes.io/component: vaultwarden-db

vaultwarden:
  fullnameOverride: vaultwarden
  statefullset:
    image:
      repository: vaultwarden/server
      tag: 1.33.1
    ports:
      web: 80
  config:
    TZ: Europe/Brussels
    DATABASE_URL: mysql://<secret:kv/data/secrets/vaultwarden-db~user>:<secret:kv/data/secrets/vaultwarden-db~password>@vaultwarden-db-service/<secret:kv/data/secrets/vaultwarden-db~name>
    ADMIN_TOKEN: <secret:kv/data/secrets/vaultwarden~admin-token>
    RUST_BACKTRACE: 1
    #    vaultwarden push notifications
    PUSH_ENABLED: true
    PUSH_INSTALLATION_ID: <secret:kv/data/secrets/vaultwarden~Installation_ID>
    PUSH_INSTALLATION_KEY: <secret:kv/data/secrets/vaultwarden~Installation_Key>
    PUSH_RELAY_URI: "https://api.bitwarden.eu"
    PUSH_IDENTITY_URI: "https://identity.bitwarden.eu"

    # disable signups, so no users can join themselves, this is invite only
    SIGNUPS_ALLOWED: false

  ingress_internal_secure:
    host: vaultwarden.<secret:kv/data/domains~domain>
    port: web
#  ingress_external_secure:
#    host: vaultwarden.<secret:kv/data/domains~domain>
#    port: web
  storage:
    - mountPath: /data
      storagePath: vaultwarden/vaultwarden
      size: 30Gi
      type: nfs-client

  probes:
    liveness:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    readiness:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 5

  resources:
    requests:
      memory: "600Mi"
      cpu: "500m"
    limits:
      memory: "800Mi"
      cpu: "1200m"
  labels:
    app.kubernetes.io/component: vaultwarden
