fullnameOverride: jackett
deployment:
  image:
    repository: linuxserver/jackett
    tag: 0.22.825@sha256:6f474d96f31a356907890334ed02855e97cce210d3b6a7d6f1be7e7ffef922d3
  ports:
    web: 9117
config:
  TZ: Europe/Brussels
  PUID: 1000
  PGID: 1000
ingress_internal:
  host: jackett.<secret:kv/data/domains~local>
  port: web
storage:
  - mountPath: /config
    storagePath: jackett/config
    size: 10Gi
    type: nfs-client
securityContext:
  fsGroup: 1000
probes:
  liveness:
    tcpSocket:
      port: web
    initialDelaySeconds: 30
    periodSeconds: 10 