{{ vaultwardendb := deepCopy . }}
{{ $_ := unset vaultwardendb ".Values" }}
{{ $_ := set vaultwardendb  "Values" .Values.vaultwardendb§ }}
{{ include "shared-lib.all" vaultwardendb }}

{{ vaultwarden := deepCopy . }}
{{ $_ := unset vaultwarden ".Values" }}
{{ $_ := set vaultwarden  "Values" .Values.vaultwarden }}
{{ include "shared-lib.all" vaultwarden }}
