{{ $vaultwardendbv := deepCopy . }}
{{ $_ := unset $vaultwardendbv ".Values" }}
{{ $_ := set $vaultwardendbv  "Values" .Values.vaultwardendb }}
{{ include "shared-lib.all" $vaultwardendbv }}

{{ $vaultwardenv := deepCopy . }}
{{ $_ := unset $vaultwardenv ".Values" }}
{{ $_ := set $vaultwardenv  "Values" .Values.vaultwarden }}
{{ include "shared-lib.all" $vaultwardenv }}
