apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
spec:
  template:
    spec:
      containers:
        - name: zigbee2mqtt
          volumeMounts:
            - name: usb
              mountPath: /dev/ttyUSB0
          securityContext:
            privileged: true
      volumes:
        - name: usb
          hostPath:
            path: /dev/zigbee
            type: CharDevice