apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/iot-zigbee-coordinator
                operator: In
                values:
                - "true"
      containers:
        - name: zigbee2mqtt
          volumeMounts:
            - name: usb
              mountPath: /dev/ttyUSB0
          securityContext:
            privileged: true
      volumes:
        - name: usb
          hostPath:
            path: /dev/zigbee
            type: CharDevice