apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: zigbee2mqtt
    path: add-zigbee-stick.yaml
