postgres-operator:
  fullnameOverride: postgres-operator

postgres-operator-ui:
  enabled: false
  fullnameOverride: postgres-operator-ui
  envs:
    targetNamespace: "*"
    teams:
      - acid
      - home
