postgres-operator:
  fullnameOverride: postgres-operator
  configConnectionPooler:
    connection_pooler_image: "bitnami/pgbouncer"

postgres-operator-ui:
  enabled: false
  fullnameOverride: postgres-operator-ui
  envs:
    targetNamespace: "*"
    teams:
      - acid
      - home
