{{- $servicePort := .Values.vault.server.service.port -}}
{{- $serviceName := include "vault.fullname" . -}}
{{- $serviceName = printf "%s-%s" $serviceName "ui" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "vault.fullname" . }}-ingress-internal
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  entryPoints: 
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress_internal.host }}`)
    services:
    - kind: Service
      name: {{ $serviceName }}
      namespace: {{ .Release.Namespace }}
      port: {{ $servicePort }}