apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.1
    helm:
      valuesObject: 
        preUpgradeChecker:
            jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 3
          taintToleration: []
          createDefaultDiskLabeledNodes: false
          defaultDataPath: ""
        global:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "dedicated"
              operator: "Equal"
              value: "master"
              effect: "NoSchedule"
        longhornManager:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "dedicated"
              operator: "Equal"
              value: "master"
              effect: "NoSchedule"

      
  destination:
    namespace: storage
    server: https://kubernetes.default.svc
  project: system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true