- name: Fetch kubeconfig
  ansible.builtin.fetch:
    become: true
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./kubeconfig/config.yaml
    flat: true
  changed_when: false

- name: Fix kubeconfig
  become: false
  ansible.builtin.replace:
    path: ./kubeconfig/config.yaml
    regexp: '127\.0\.0\.1'
    replace: "{{ k3s_master_domain_name }}"
  changed_when: false
  delegate_to: localhost
  run_once: true

- name: Fix kubeconfig
  become: false
  ansible.builtin.replace:
    path: ./kubeconfig/config.yaml
    regexp: 'default'
    replace: "{{ k3s_cluster_name | default('k3s') }}"
  changed_when: false
  delegate_to: localhost
  run_once: true

# - name: Merge kubeconfig to config
#   become: false
#   ansible.builtin.shell:
#     cmd: |
#     KUBECONFIG=~/.kube/config:./playbooks/kubeconfig/config.yaml kubectl config view --merge --flatten > ~/.kube/config2
#     mv ~/.kube/config2 ~/.kube/config
#     rm -f ./kubeconfig/config.yaml
#     rm -rf ~/.kube/config2
#   changed_when: false
#   delegate_to: localhost

