- name: Wait for node-token
  ansible.builtin.wait_for:
    path: "/var/lib/rancher/k3s/server/node-token"

- name: Register node-token file access mode
  ansible.builtin.stat:
    path: "/var/lib/rancher/k3s/server/node-token"
  register: p

- name: Change file access node-token
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/node-token"
    mode: "g+rx,o+rx"

- name: Read node-token from master
  ansible.builtin.slurp:
    path: "/var/lib/rancher/k3s/server/node-token"
  register: k3s_token

- name: Store Master node-token
  ansible.builtin.set_fact:
    token: "/var/lib/rancher/k3s/server/node-token"

- name: Restore node-token file access
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/node-token"
    mode: "{{ p.stat.mode }}"

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
