apiVersion: v1
kind: Secret
metadata:
  name: services-db
  namespace: services
type: Opaque
data:
  sonarr_user: <secret:kv/data/services~sonarr_user | base64>
  sonarr_password: <secret:kv/data/services~sonarr_password | base64>
  radarr_user: <secret:kv/data/services~radarr_user | base64>
  radarr_password: <secret:kv/data/services~radarr_password | base64>
  prowlarr_user: <secret:kv/data/services~prowlarr_user | base64>
  prowlarr_password: <secret:kv/data/services~prowlarr_password | base64>
  bazarr_user: <secret:kv/data/services~bazarr_user | base64>
  bazarr_password: <secret:kv/data/services~bazarr_password | base64>
  jellyseerr_user: <secret:kv/data/services~jellyseerr_user | base64>
  jellyseerr_password: <secret:kv/data/services~jellyseerr_password | base64>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-db
  namespace: services
data:
  host: service-db-postgresql-hl
  port: "5432"
  sonarr_database: sonarr_main
  sonarr_database_logs: sonarr_log
  radarr_database: radarr_main
  radarr_database_logs: radarr_log
  prowlarr_database: prowlarr_main
  prowlarr_database_logs: prowlarr_log
  bazarr_database: bazarr_main
  jellyseerr_database: jellyseerr



