apiVersion: v1
kind: PersistentVolume
metadata:
  name: services-series
  namespace: services
  labels:
    type: local
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: "<secret:kv/data/storage/nfs~series-path>"
  mountOptions:
    - vers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: services-video
  namespace: services
  labels:
    type: local
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: "<secret:kv/data/storage/nfs~videos-path>"
  mountOptions:
    - vers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: services-downloads
  namespace: services
  labels:
    type: local
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: "<secret:kv/data/storage/nfs~downloads-path>"
  mountOptions:
    - vers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-video
  namespace: services
spec:
  resources:
    requests:
      storage: 8Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName:  services-video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-downloads
  namespace: services
spec:
  resources:
    requests:
      storage: 8Ti
  volumeName: services-downloads
  storageClassName: ""
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-series
  namespace: services
spec:
  resources:
    requests:
      storage: 8Ti
  volumeName: services-series
  storageClassName: ""
  accessModes:
    - ReadWriteMany
