apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-data
  namespace: smarthome
  annotations:
    nfs.io/storage-path: "piper/data"
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi