apiVersion: v2
name: peanut
description: PeaNUT web UI for the NUT server (APC Back-UPS BX1600MI)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: shared-lib
    version: 0.1.0
    repository: file://../../../lib/shared-lib
