redis:
  syncWave: -10
  fullnameOverride: manyfold-redis
  statefulset:
    image:
      repository: redis
      tag: "7.4-alpine"
    ports:
      redis: 6379
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi
  labels:
    app.kubernetes.io/component: manyfold-redis

app:
  fullnameOverride: manyfold
  podSecurityContext:
    fsGroup: 1000
  deployment:
    image:
      repository: ghcr.io/manyfold3d/manyfold
      tag: "0.149.0"
    ports:
      http: 3214
  config:
    TZ: Europe/Brussels
    PUID: "1000"
    PGID: "1000"
    SECRET_KEY_BASE: <secret:kv/data/apps/manyfold~secret_key_base>
    REDIS_URL: redis://manyfold-redis-service:6379/1
    DATABASE_ADAPTER: postgresql
    DATABASE_HOST: apps-db-pg-rw
    DATABASE_PORT: "5432"
    DATABASE_USER: manyfold_user
    DATABASE_PASSWORD: <secret:kv/data/apps/manyfold~db_password>
    DATABASE_NAME: manyfold
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  ingress_internal_secure:
    host: manyfold.<secret:kv/data/domains~domain>
    port: http
  storage:
    - mountPath: /models
      size: 100Gi
      type: longhorn
      volumeName: manyfold-models
      nameSuffix: models
  labels:
    app.kubernetes.io/component: manyfold
