apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: system
  source:
    chart: node-feature-discovery
    repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    targetRevision: v0.15.3
    helm:
      releaseName: node-feature-discovery
      values: |
        worker:
          config:
            core:
              labelSources: 
                - "custom"

            sources:
              custom:
                - name: "zigbee-coordinator-test"
                  labels: 
                    feature.node.kubernetes.io/iot-zigbee-coordinator: "true"
                  matchFeatures:
                    - feature: usb.device
                      matchExpressions:
                        vendor: { op: In, value: ["10c4"] }
                        device: { op: In, value: ["ea60"] }
                        serial: { op: In, value: ["54d39955bc39ec118f02e3680aac08d5"] }

  destination:
    server: "https://kubernetes.default.svc"
    namespace: node-feature-discovery
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
