apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-series
  namespace: arr-stack
  labels:
    type: local
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: "<secret:kv/data/storage/nfs~series-path>"
  mountOptions:
    - vers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-video
  namespace: arr-stack
  labels:
    type: local
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: "<secret:kv/data/storage/nfs~videos-path>"
  mountOptions:
    - vers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-downloads
  namespace: arr-stack
  labels:
    type: local
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <secret:kv/data/storage/nfs~server-ip>
    path: "<secret:kv/data/storage/nfs~downloads-path>"
  mountOptions:
    - vers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-video
  namespace: arr-stack
spec:
  resources:
    requests:
      storage: 8Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: arr-stack-video
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-downloads
  namespace: arr-stack
spec:
  resources:
    requests:
      storage: 8Ti
  volumeName: arr-stack-downloads
  storageClassName: ""
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-series
  namespace: arr-stack
spec:
  resources:
    requests:
      storage: 8Ti
  volumeName: arr-stack-series
  storageClassName: ""
  accessModes:
    - ReadWriteMany
