
apiVersion: v1
kind: Secret
metadata:
  name: chap-secret
type: "kubernetes.io/iscsi-chap"
data:
  discovery.sendtargets.auth.username: <secret:kv/data/storage/iscsi~username | base64>
  discovery.sendtargets.auth.password: <secret:kv/data/storage/iscsi~password | base64>
  node.session.auth.username: <secret:kv/data/storage/iscsi~username | base64>
  node.session.auth.password: <secret:kv/data/storage/iscsi~password | base64>