fullnameOverride: mqtt-playground
statefulset:
  image:
    repository: ghcr.io/coollision/mqtt-go-playground
    tag: latest
    imagePullPolicy: Always
config:
  LOGLEVEL: INFO
  MQTT_BROKERADDRESS: <secret:kv/data/workload/smarthome/mqtt-playground~broker-address>
  MQTT_BROKERID: <secret:kv/data/workload/smarthome/mqtt-playground~broker-id>
  MQTT_BROKERUSER: <secret:kv/data/workload/smarthome/mqtt-playground~broker-user>
  MQTT_BROKERPASSWORD: <secret:kv/data/workload/smarthome/mqtt-playground~broker-password>

keel:
  policy: force
  pollSchedule: "@every 1m"

disableService: true
