apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whisper
  namespace: smarthome
spec:
  serviceName: whisper
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper:3.0.2
          args:
          # https://github.com/rhasspy/wyoming-faster-whisper/blob/master/wyoming_faster_whisper/__main__.py
            - --data-dir
            - /data
            - --download-dir
            - /download
            - --language
            - nl
            - --model
            - medium-int8
            - --beam-size
            - "3"
            - --compute-type
            - int8
            - --device
            - cpu
            - --num-workers
            - "2"
            - --vad-filter
            - --initial-prompt
            - "Dutch speech transcription"

          env:
            - name: TZ
              value: Europe/Brussels
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "3000m"
          ports:
            - containerPort: 10300
              name: whisper
              protocol: TCP
          volumeMounts:
            - name: whisper-data
              mountPath: /data
            - name: whisper-download
              mountPath: /download
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: whisper-data
        - name: whisper-download
          persistentVolumeClaim:
            claimName: whisper-download
