kube-fledged:
  args:
    controllerImageCacheRefreshFrequency: 0s
    controllerCRISocketPath: /run/k3s/containerd/containerd.sock
    controllerImagePullPolicy: Always
    # increase the controllerImagePullDeadlineDuration to 20m to allow for slower image pulls
    controllerImagePullDeadlineDuration: 20m

    # enable to debug controller 
    # controllerJobRetentionPolicy: retain

  # disable the webhook server and validating webhook
  # cause its ginving a tls error
  webhookServer:
    enable: false
  validatingWebhook:
    # Specifies whether a validating webhook configuration should be created
    create: false
  
  resources:
    requests:
      cpu: 5m
      memory: 20Mi
    limits:
      cpu: 5m
      memory: 25Mi