#!/usr/bin/env bash
# Regenerates the "scale-to-zero autogen" region inside applications/set-workloads.yaml
# and applications/set-system.yaml from every workload/system app's `scaleToZero.enabled`
# flag. Full regeneration each run (not incremental), so adding AND removing the flag
# both just work: the region always reflects exactly the current set of flagged apps.
#
# Exits 1 (after rewriting the files) if anything changed relative to what's committed/
# staged — used as both a pre-commit hook (blocks the commit for review) and a CI check
# (fails the build if the committed files are stale).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

BEGIN_MARKER="        # BEGIN scale-to-zero autogen — generated by scripts/gen-scale-to-zero-ignores.sh, do not hand-edit"
END_MARKER="        # END scale-to-zero autogen"

# Prints "<namespace>\t<name>\t<kind>" for every app under $1 (workload|system) whose
# values.yaml has scaleToZero.enabled == true. Skips disabled-* app directories. <kind>
# is Deployment or StatefulSet, based on which top-level key the app's values.yaml uses
# — ArgoCD's ignoreDifferences match is scoped by kind, so getting this wrong means the
# rule silently never matches the real resource (a StatefulSet flagged as Deployment
# would keep getting selfHeal-reverted with zero indication anything was wrong).
collect_entries() {
  local tree="$1"
  local values_file dir base parent namespace enabled kind has_deployment has_statefulset
  for values_file in "$tree"/*/*/values.yaml; do
    [ -e "$values_file" ] || continue
    dir=$(dirname "$values_file")
    base=$(basename "$dir")
    case "$base" in disabled-*) continue ;; esac
    parent=$(dirname "$dir")
    namespace=$(basename "$parent")
    enabled=$(yq '.scaleToZero.enabled // false' "$values_file")
    if [ "$enabled" = "true" ]; then
      has_deployment=$(yq '.deployment // false' "$values_file")
      has_statefulset=$(yq '.statefulset // false' "$values_file")
      if [ "$has_statefulset" != "false" ]; then
        kind="StatefulSet"
      elif [ "$has_deployment" != "false" ]; then
        kind="Deployment"
      else
        echo "ERROR: $values_file has scaleToZero.enabled=true but neither a 'deployment:' nor 'statefulset:' key — can't determine resource kind, refusing to guess." >&2
        exit 2
      fi
      printf '%s\t%s\t%s\n' "$namespace" "$base" "$kind"
    fi
  done
}

# Rebuilds the marked region in $1 from the app tree $2. Uses plain head/tail/grep
# (not awk -v with a multi-line value, which BSD awk rejects) to splice the block
# between the marker lines, inclusive of the markers themselves.
splice() {
  local target="$1" tree="$2"
  local entries namespace name kind block_file begin_line end_line

  entries=$(collect_entries "$tree" | sort)

  block_file=$(mktemp)
  if [ -n "$entries" ]; then
    while IFS=$'\t' read -r namespace name kind; do
      cat >>"$block_file" <<EOF
        - group: apps
          kind: ${kind}
          name: ${name}
          namespace: ${namespace}
          jsonPointers:
            - /spec/replicas
EOF
    done <<<"$entries"
  fi

  begin_line=$(grep -nF "$BEGIN_MARKER" "$target" | head -1 | cut -d: -f1)
  end_line=$(grep -nF "$END_MARKER" "$target" | head -1 | cut -d: -f1)

  # Refuse to touch the file if the markers are missing or out of order — better to
  # fail loudly here than to feed empty/bogus line numbers to head/tail and silently
  # produce a mangled file.
  if [ -z "$begin_line" ] || [ -z "$end_line" ]; then
    echo "ERROR: scale-to-zero markers not found in $target — refusing to modify it. Expected exactly these two lines to exist:" >&2
    echo "  $BEGIN_MARKER" >&2
    echo "  $END_MARKER" >&2
    rm -f "$block_file"
    exit 2
  fi
  if [ "$begin_line" -ge "$end_line" ]; then
    echo "ERROR: BEGIN marker (line $begin_line) is not before END marker (line $end_line) in $target — refusing to modify it." >&2
    rm -f "$block_file"
    exit 2
  fi

  {
    head -n "$begin_line" "$target"
    cat "$block_file"
    tail -n "+$end_line" "$target"
  } >"$target.tmp"
  mv "$target.tmp" "$target"
  rm -f "$block_file"
}

splice applications/set-workloads.yaml workload
splice applications/set-system.yaml system

if ! git diff --quiet -- applications/set-workloads.yaml applications/set-system.yaml; then
  echo "scale-to-zero ignoreDifferences regenerated (files changed) — review and re-stage:" >&2
  git --no-pager diff -- applications/set-workloads.yaml applications/set-system.yaml >&2 || true
  exit 1
fi

exit 0
