apiVersion: v2
name: sonarr
description: A Helm chart for Sonarr
type: application
version: 0.1.0
appVersion: "4.0.16"

dependencies:
  - name: arr-lib
    version: 0.1.0
    repository: file://../../../lib/arr-lib
