fullnameOverride: flaresolverr
deployment:
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: v3.3.21@sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b
  ports:
    web: 8191
config:
  TZ: Europe/Brussels
  PUID: 1000
  PGID: 1000

securityContext:
  fsGroup: 1000
probes:
  liveness:
    tcpSocket:
      port: web
    initialDelaySeconds: 30
    periodSeconds: 10 