node-feature-discovery:
  fullnameOverride: node-feature-discovery
  gc:
    resources:
      requests:
        cpu: 5m
        memory: 15Mi
      limits:
        cpu: 5m
        memory: 25Mi
  master:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 75m
        memory: 75Mi

  worker:
    resources:
      requests:
        cpu: 15m
        memory: 30Mi
      limits:
        cpu: 20m
        memory: 40Mi
    config:
      core:
        labelSources: 
          - "custom"

      sources:
        custom:
          - name: "zigbee-coordinator"
            labels: 
              feature.node.kubernetes.io/iot-zigbee-coordinator: "true"
            matchFeatures:
              - feature: usb.device
                matchExpressions:
                  vendor: { op: In, value: ["10c4"] }
                  device: { op: In, value: ["ea60"] }
                  serial: { op: In, value: ["54d39955bc39ec118f02e3680aac08d5"] }

descheduler:
  fullnameOverride: descheduler
  kind: Deployment
  deschedulingInterval: 1m
  cmdOptions:
    v: 3
  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: "DefaultEvictor"
            args:
              evictLocalStoragePods: true
          - name: "RemoveDuplicates"
          - name: "RemovePodsHavingTooManyRestarts"
            args:
              podRestartThreshold: 15
              includingInitContainers: true
          - name: "RemovePodsViolatingNodeAffinity"
            args:
              nodeAffinityType:
              - "requiredDuringSchedulingIgnoredDuringExecution"
          - name: "RemovePodsViolatingInterPodAntiAffinity"
          - name: "RemovePodsViolatingTopologySpreadConstraint"
          - name: "RemovePodsViolatingNodeTaints"
          - name: "LowNodeUtilization"
            args:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
        plugins:
          balance:
            enabled:
              - "RemoveDuplicates"
              - "RemovePodsViolatingTopologySpreadConstraint"
              - "LowNodeUtilization"
          deschedule:
            enabled:
              - "RemovePodsHavingTooManyRestarts"
              - "RemovePodsViolatingNodeTaints"
              - "RemovePodsViolatingNodeAffinity"
              - "RemovePodsViolatingInterPodAntiAffinity"

  service:
    enabled: true
  serviceMonitor:
    enabled: true
  
  resources:
    requests:
      cpu: 100m
      memory: 30Mi
    limits:
      cpu: 120m
      memory: 40Mi