apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-tunnels-operator
subjects:
  - kind: ServiceAccount
    name: aws-tunnels-operator
    namespace: proxies
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-tunnels-operator
