fullnameOverride: tautulli
statefullset:
  image:
    repository: linuxserver/tautulli
    tag: latest
  ports:
    web: 8181
config:
  TZ: Europe/Brussels
  PUID: 1000
  PGID: 1000
ingress_internal:
  host: tautulli.<secret:kv/data/domains~local>
  port: web
storage:
  - mountPath: /config
    storagePath: tautulli/config
    size: 10Gi
    type: nfs-client
securityContext:
  fsGroup: 1000
probes:
  liveness:
    httpGet:
      path: /
      port: web
    initialDelaySeconds: 30
    periodSeconds: 10 


keel:
  enabled: true
  policy: force
  pollSchedule: "@midnight"