fullnameOverride: tautulli
statefullset:
  image:
    repository: linuxserver/tautulli
    tag: latest
    imagePullPolicy: Always
  ports:
    web: 8181
config:
  TZ: Europe/Brussels
  PUID: 1000
  PGID: 1000
ingress_internal:
  host: tautulli.<secret:kv/data/domains~local>
  port: web
storage:
  - type: longhorn
    mountPath: /config
    size: 2Gi
    nameSuffix: config
    volumeName: arr-stack-tautulli-config
    protect: true
podSecurityContext:
  fsGroup: 1000
probes:
  liveness:
    httpGet:
      path: /
      port: web
    initialDelaySeconds: 30
    periodSeconds: 10


keel:
  policy: force
  pollSchedule: "@midnight"
