metallb:
  fullnameOverride: metallb
  controller:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  speaker:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      enabled: true
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 5
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        memory: 128Mi
    frr:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 192Mi
    frrMetrics:
      resources:
        requests:
          cpu: 5m
          memory: 24Mi
        limits:
          cpu: 50m
          memory: 64Mi
    reloader:
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 25m
          memory: 32Mi
