{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-tunnels-operator.fullname" . }}-auth
  namespace: {{ include "aws-tunnels-operator.namespace" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "aws-tunnels-operator.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.authPort }}
      targetPort: auth
{{- end }}
