{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-tunnels-operator.serviceAccountName" . }}
  namespace: {{ include "aws-tunnels-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-tunnels-operator.name" . }}
{{- end }}
