apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: services
  annotations:
    nfs.io/storage-path: "sonarr/config"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: services
spec:
  serviceName: sonarr
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
      name: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        name: sonarr
    spec:
      initContainers:
        - name: sonarr-init
          image: alpine
          command: 
            - "/bin/sh"
            - "-c"
            - cp /init/script.sh /tmp && chmod +x /tmp/script.sh && /tmp/script.sh
          resources: {}
          env:
            - name: CONFIG_FILE
              value: "../config/config.xml"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: services-db
                  key: sonarr_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: services-db
                  key: sonarr_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-db
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-db
                  key: port
            - name: POSTGRES_MAIN_DB
              valueFrom:
                configMapKeyRef:
                  name: service-db
                  key: sonarr_database
            - name: POSTGRES_LOG_DB
              valueFrom:
                configMapKeyRef:
                  name: service-db
                  key: sonarr_database_logs
          volumeMounts:
            - mountPath: /init
              name: arr-init-script
            - mountPath: /config
              name: sonarr-config
      containers:
        - image: linuxserver/sonarr:4.0.13
          name: sonarr
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Brussels
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 8989
              name: web
              protocol: TCP
          resources:
            requests:
              memory: 500Mi
              cpu: 400m
            limits:
              memory: 800Mi
              cpu: 600m
          readinessProbe:
            httpGet:
              port: 8989
              path: /ping
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8989
              path: /ping
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-downloads
              mountPath: /data/downloads
            - name: sonarr-series
              mountPath: /data/series
      volumes:
        - name: arr-init-script
          configMap:
            name: arr-init-script
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-downloads
          persistentVolumeClaim:
            claimName: services-downloads
        - name: sonarr-series
          persistentVolumeClaim:
            claimName: services-series
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: sonarr-web
  namespace: services
spec:
  ports:
    - name: web
      port: 8989
      targetPort: web
  selector:
    name: sonarr
    app: sonarr
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress
  namespace: services
spec:
  entryPoints: 
    - web
  routes:
    - kind: Rule
      match: Host(`sonarr.<secret:kv/data/domains~local>`)
      priority: 0
      services:
        - kind: Service
          name: sonarr-web
          namespace: services
          port: 8989

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingress-secure
  namespace: services
spec:
  entryPoints: 
    - websecure
  routes:
    - kind: Rule
      match: host(`sonarr.<secret:kv/data/domains~domain>`)
      priority: 0
      services:
        - kind: Service
          name: sonarr-web
          namespace: services
          port: 8989
  tls: {}

# pgloader --with "quote identifiers" --with "data only" --with "prefetch rows = 100" --with "batch size = 1MB" sonarr.db 'postgresql://user:password@postgres-deployment-postgresql-hl/sonarr_main'
# pgloader --with "quote identifiers" --with "data only" --with "prefetch rows = 100" --with "batch size = 1MB" log.db 'postgresql://user:password@postgres-deployment-postgresql-hl/sonarr_log'