fullnameOverride: sonarr

statefulset:
  image:
    repository: linuxserver/sonarr
    tag: "4.0.17"
    imagePullPolicy: Always
  ports:
    web: 8989

config:
  TZ: Europe/Brussels
  PUID: "1000"
  PGID: "1000"

resources:
  requests:
    memory: 500Mi
    cpu: 400m
  limits:
    memory: 800Mi
    cpu: 600m

probes:
  readiness:
    httpGet:
      port: 8989
      path: /ping
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    httpGet:
      port: 8989
      path: /ping
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

ingress_internal:
  host: sonarr.<secret:kv/data/domains~local>
  port: web

ingress_external_secure:
  host: sonarr.<secret:kv/data/domains~domain>
  port: web

storage:
  - mountPath: /config
    type: longhorn
    size: 8Gi
    nameSuffix: config
    volumeName: arr-stack-sonarr-config
    protect: true
  - mountPath: /data/downloads
    type: existingClaim
    claimName: services-downloads
    nameSuffix: downloads
  - mountPath: /data/series
    type: existingClaim
    claimName: services-series
    nameSuffix: series

podSecurityContext:
  fsGroup: 1000

initContainers:
  - name: sonarr-init
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - cp /init/script.sh /tmp && chmod +x /tmp/script.sh && /tmp/script.sh
    resources: {}
    env:
      - name: CONFIG_FILE
        value: /config/config.xml
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: services-db
            key: sonarr_user
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: services-db
            key: sonarr_password
      - name: POSTGRES_HOST
        valueFrom:
          configMapKeyRef:
            name: service-db
            key: host
      - name: POSTGRES_PORT
        valueFrom:
          configMapKeyRef:
            name: service-db
            key: port
      - name: POSTGRES_MAIN_DB
        valueFrom:
          configMapKeyRef:
            name: service-db
            key: sonarr_database
      - name: POSTGRES_LOG_DB
        valueFrom:
          configMapKeyRef:
            name: service-db
            key: sonarr_database_logs
    volumeMounts:
      - mountPath: /init
        name: arr-init-script
      - mountPath: /config
        name: sonarr-config

extraVolumes:
  - name: arr-init-script
    configMap:
      name: arr-init-script
