apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openwakeword
  namespace: smarthome
spec:
  serviceName: openwakeword
  selector:
    matchLabels:
      app: openwakeword
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
        - name: openwakeword
          image: rhasspy/wyoming-openwakeword:2.0.0
          env:
          - name: TZ
            value: Europe/Brussels
          resources: {}
          ports:
            - containerPort: 10400
              name: openwakeword
              protocol: TCP
          volumeMounts:
            - name: openwakeword-data
              mountPath: /data
      volumes:
          - name: openwakeword-data
            persistentVolumeClaim:
              claimName: openwakeword-data