apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: services
spec:
  storageClassName: nfs-client-name-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
