volumes:
  - name: monitoring-alertmanager
    claimName: monitoring-alertmanager
    mountPath: /data-allertmanager
    size: 2Gi
  - name: monitoring-grafana
    claimName: monitoring-grafana
    mountPath: /data-grafana
    size: 2Gi
  - name: monitoring-prometheus
    claimName: monitoring-prometheus
    mountPath: /data-prometheus
    size: 10Gi
image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent
